# Una vez que ya hayas subido tu archivo, seguro querrás
# visualizarlo, para esto utilizas el endpoint /v1/files/fromsession

# La cabecera "Authorization" es de caracter obligatorio y su formato
# debe ser exactamente igual al que se muestra en el ejemplo,
# el JWT Key obtenido al iniciar sesión debe reemplazar "TU-JWT-KEY-AQUI".

GET http://127.0.0.1:81/api/v1/files/fromsession HTTP/1.1
content-type: application/json
Authorization: Bearer TU-JWT-KEY-AQUI

{
}